name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - main  # Change this if you want a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.GCP_VM_IP }} >> ~/.ssh/known_hosts

      - name: Deploy Code to Google Cloud VM
        run: |
          rsync -avz --delete -e "ssh -i ~/.ssh/id_rsa" ./ ${{ secrets.GCP_VM_USER }}@${{ secrets.GCP_VM_IP }}:${{ secrets.GCP_VM_PATH }}

      - name: Restart Application
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.GCP_VM_USER }}@${{ secrets.GCP_VM_IP }} << 'EOF'
            cd ${{ secrets.GCP_VM_PATH }}
            docker-compose down || pm2 stop all || systemctl stop myapp
            git pull origin main
            docker-compose up -d || pm2 restart all || systemctl start myapp
          EOF
